"""add is_verified to users

Revision ID: 9eca03f167bd
Revises: 9d2936f5605d
Create Date: 2026-01-03 15:49:52.436412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eca03f167bd'
down_revision: Union[str, Sequence[str], None] = '9d2936f5605d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('jobs', sa.Column('experience', sa.INTEGER(), nullable=True))
    op.alter_column('jobs', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
